### ISSUE TITLE
Suggestions about exeinfopeRUN.cfg

### ISSUE THREAD

**Issue by StrollStars** [ExeinfoASL/ASL#2]
I recommend that it supports parameters whether running an external exe or running the exe which is scanned.

**Comment by ExeinfoASL** [comment]
Give me example please , how you like ?

**Comment by StrollStars** [comment]
For example, I used exeinfope.exe to scan test.rar, and then I click the _External_ _exe_ _Run_.
If the item is _WinRAR.exe_ in exeinfopeRUN.cfg, exeinfope.exe start WinRAR.exe and WinRAR.exe open the test.rar.
But if the item is _WinRAR.exe_ _e_ _G:\temp_, exeinfope.exe shows _Not_ _found_. I hope WinRAR.exe can extract the files to the G:\temp.

BTW, I hope the configuration is stored in the directory where the program is located instead of the registry.

**Comment by ExeinfoASL** [comment]
I think about this , but you can create bat file and run bat file from Exeinfo

**Comment by StrollStars** [comment]
Won't you add such features in the future?
There are some problems about bat file, such as how to import the paths of the scanned files.

**Comment by ExeinfoASL** [comment]
I try to fix it , try contact via email

**Comment by StrollStars** [comment]
OK, but I didn't find your email address.

**Comment by ExeinfoASL** [comment]
asl@onet.eu 
or
asl.exeinfo@gmail.com

**Comment by StrollStars** [comment]
Thank you.
I close this issues.

**Comment by StrollStars** [comment]
Thank you.
I close this issues.

**Comment by ExeinfoASL** [comment]
I tested fix not needed

You must create bat file : winrarEXTR.bat 
inside bat : "c:\Program Files\WinRar\winrar.exe" x %1 G:\temp
and Edit : exeinfopeRUN.cfg file and add line : winrarEXTR.bat
work ok

**Comment by StrollStars** [comment]
> I tested fix not needed
> 
> You must create bat file : winrarEXTR.bat
> inside bat : "c:\Program Files\WinRar\winrar.exe" x %1 G:\temp
> and Edit : exeinfopeRUN.cfg file and add line : winrarEXTR.bat
> work ok

I do it, Thank you.
