### ISSUE TITLE
rdtsc<4=1

### ISSUE THREAD

**Issue by jimdi** [ExeinfoASL/ASL#4]
when open exeinfope from shell menu get subj error 

when open exeinfope and drag'n'drop file all ok

what i do wrong? version is 0.0.6.3 on Win10

**Comment by ExeinfoASL** [comment]
Maybe you have very fast computer or very slow.
This is protection for debug tracing , i check this.

**Comment by ExeinfoASL** [comment]
Fixed , wait for version 0.0.6.4

**Comment by jimdi** [comment]
is that your e-mail address: asl.exeinfo@gmail.com? i worried because found only asl@onet.eu, but receive mail from gmail

**Comment by ExeinfoASL** [comment]
Yes , i send from gmail , onet.eu often drop to Spam directory
 
 
A.S.L.
 
 
W dniu 2020-12-21 14:57:33 użytkownik Jim_Di <notifications@github.com> napisał:
 
is that your e-mail address: asl.exeinfo@gmail.com? i worried because found only asl@onet.eu, but receive mail from gmail

**Comment by jimdi** [comment]
new version works for me, thx!
