### ISSUE TITLE
Bug with Overlay

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [ExeinfoASL/ASL#5]
**Steps to bug:**
1. Select any exe with overlay
2. **>>** - **Overlay Menu** - **Save Overlay as \*.ovl (if exists)** _| save to any file_
3. **>>** - **Overlay Menu** - **Trunk overlay (generate new file)** _| save to any file_

If you look at the generated exe without overlay, then the exe invalid (not copied at offset 0x0).
But if you restart ExeinfoPE after step 2, then step 3 will generate the correct exe.
I have been seeing this error for 1 year, if not more.

This file consists of overlay parts
![изображение](https://user-images.githubusercontent.com/17485135/106727325-cc74e200-6624-11eb-91bc-0578a5cd05d6.png)

**Comment by ExeinfoASL** [comment]
Yes , I use buffer to copy overlay and loading original data was over written. 
If you first save exe without overlay and later save overlay work ok.
I can fix it.Not a bug .I know this.

**Comment by Ze2QvoQxxKeu** [comment]
> I can fix it.Not a bug .I know this.

Fix it, please. I often use functions in this order.

**Comment by ExeinfoASL** [comment]
fixed , you must wait for version : 0.0.6.5 III

**Comment by Ze2QvoQxxKeu** [comment]
Big thanks😃
