### ISSUE TITLE
Error reported when running.

### ISSUE THREAD

**Issue by LanYunDev** [ExeinfoASL/ASL#6]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/95263282/164913719-66fe21a7-9398-43ab-86c9-afe1c6ab5ad3.png">
This is the system information of windows 11 under my virtual machine.
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/95263282/164913848-26e89086-8f54-4e20-b6b4-f86f6e8d7889.png">
This flashback is known to occur on all versions.
I hope the developers can troubleshoot this.
I can provide any information that can help you.

**Comment by ExeinfoASL** [comment]
Exeinfo ver.0.0.6.9  this adress : 0025E30C   ?

 

From: LanYun ***@***.*** 
Sent: Saturday, April 23, 2022 6:05 PM
To: ExeinfoASL/ASL
Cc: Subscribed
Subject: [ExeinfoASL/ASL] Error reported when running. (Issue #6)

 

 <https://user-images.githubusercontent.com/95263282/164913719-66fe21a7-9398-43ab-86c9-afe1c6ab5ad3.png> image

This is the system information of windows 11 under my virtual machine. 

 <https://user-images.githubusercontent.com/95263282/164913848-26e89086-8f54-4e20-b6b4-f86f6e8d7889.png> image

This flashback is known to occur on all versions. I hope the developers can troubleshoot this. I can provide any information that can help you.

**Comment by LanYunDev** [comment]
Yes.

**Comment by ExeinfoASL** [comment]
I send Email to :  ***@***.***

**Comment by ExeinfoASL** [comment]
You tested fixed version ?

**Comment by LanYunDev** [comment]
In fact, I have tested several versions and this error occurs in all of them.

**Comment by ExeinfoASL** [comment]
few days ago I sent link to you via email - and link to fixed version
you tested ?

**Comment by LanYunDev** [comment]
Sorry, I just saw the test software you sent me, just tested it and found that there are still problems.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/95263282/166105554-01797a5f-c868-4689-94d2-bc1cf824c047.png">

**Comment by ExeinfoASL** [comment]
check this version , I rewrite code to : nop nop nop ...
link :
https://app.box.com/s/0j53czzfl8fd3cj2ttaukqb2bapt7sd3

**Comment by LanYunDev** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/95263282/166115840-25749aea-7108-446e-989c-70106af61ed6.png">
It seems to be able to open correctly

**Comment by LanYunDev** [comment]
Thank you very much, it seems to be working properly now.

**Comment by ExeinfoASL** [comment]
Exeinfo Pe is crypted with my crypter , written in 2018.
Not tested with Windows 11  system
I must fix it
:-)
